"""Core module for Crypto Quant Pro."""

from .engines import (
    BacktestingEngine,
    EventDispatcher,
    PaperTradingEngine,
    TradingEngine,
)
from .engines.abu_engine_adapter import AbuEngineAdapter
from .risk import (
    AbuPositionAdapter,
    OptimizationConfig,
    OptimizationMethod,
    PortfolioOptimizer,
    PositionConfig,
    PositionLimit,
    PositionManager,
    RiskCalculator,
    RiskMetrics,
    StopLossConfig,
    StopLossManager,
    StopLossType,
)
from .strategies import (
    AbuBuyFactorAdapter,
    AbuSellFactorAdapter,
    BaseStrategy,
    BreakoutStrategy,
    MovingAverageCrossStrategy,
    RSIStrategy,
    StopLossStrategy,
    StrategyDirection,
    StrategyRegistry,
    StrategySignal,
    TakeProfitStrategy,
    TrailingStopStrategy,
    register_legacy_strategies,
)

__all__ = [
    "TradingEngine",
    "BacktestingEngine",
    "PaperTradingEngine",
    "EventDispatcher",
    "AbuEngineAdapter",
    "BaseStrategy",
    "StrategySignal",
    "StrategyDirection",
    "StrategyRegistry",
    "MovingAverageCrossStrategy",
    "BreakoutStrategy",
    "RSIStrategy",
    "StopLossStrategy",
    "TakeProfitStrategy",
    "TrailingStopStrategy",
    "AbuBuyFactorAdapter",
    "AbuSellFactorAdapter",
    "register_legacy_strategies",
    "PositionManager",
    "PositionConfig",
    "PositionLimit",
    "RiskCalculator",
    "RiskMetrics",
    "StopLossManager",
    "StopLossConfig",
    "StopLossType",
    "PortfolioOptimizer",
    "OptimizationConfig",
    "OptimizationMethod",
    "AbuPositionAdapter",
]
